name: kaniko-action
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  push:
    branches:
      - '**'
jobs:
  build:
    steps:
    - name: get source code
      uses: docker://alpine/git:v2.36.3
      run: |
        git clone https://${{secrets.GIT_SECRET_ACCESS_TOKEN}}@github.com/cloudbees-io/kaniko -b ${{ cloudbees.scm.branch }} .
    - name: Unit tests
      uses: docker://golang:1.20-alpine3.18
      run: |
        go test --cover ./...
    - name: Write docker config.json
      uses: docker://alpine:3.18
      env:
        DOCKERCONFIGJSON: ${{ secrets.dockerconfigjson }}
      run: |
        mkdir -p $HOME/.docker
        echo "$DOCKERCONFIGJSON" > $HOME/.docker/config.json
    - name: docker build and publish
      uses: cloudbees-io/kaniko@v1
      with:
        destination: ${{ vars.STAGING_DOCKER_REGISTRY }}/staging/kaniko-action:${{ cloudbees.scm.sha }}${{ cloudbees.scm.branch == 'main' && format(',{0}/staging/kaniko-action:0.0.9,{0}/staging/kaniko-action:latest', vars.STAGING_DOCKER_REGISTRY)  || format(',{0}/staging/kaniko-action:{1}', vars.STAGING_DOCKER_REGISTRY, cloudbees.version) }}
        labels: maintainer=sdp-pod-3,email=engineering@cloudbees.io
        context: ${{ cloudbees.workspace }}
  
  test:
    needs: [build]
    steps:
    - name: Get source code
      uses: docker://alpine/git:v2.36.3
      run: |
        git clone https://${{secrets.GIT_SECRET_ACCESS_TOKEN}}@github.com/cloudbees-io/kaniko -b ${{ cloudbees.scm.branch }} .
    - name: Write docker config.json
      uses: docker://alpine:3.18
      env:
        DOCKERCONFIGJSON: ${{ secrets.dockerconfigjson }}
      run: |
        mkdir -p $HOME/.docker
        echo "$DOCKERCONFIGJSON" > $HOME/.docker/config.json
    - name: Build test image
      uses: ./
      with:
        dockerfile: Dockerfile-test
        destination: registry.saas-dev.beescloud.com/staging/kaniko-action-test:${{ cloudbees.scm.sha }}
        skip-default-registry-fallback: 'false'
